custom_init_commands:
- /replaceitem entity @s weapon.mainhand minecraft:iron_pickaxe
- /execute as @p at @s run fill ~ ~ ~ ~1 ~-5 ~ diamond_ore
- /tp @s ~ ~-10 ~
defaults:
- base
- _self_
text: Locate and mine diamond ore in the underground layers of the world.
reward_cfg:
- event: mine_block
  identity: mine_diamond_ore
  objects:
  - diamond_ore
  reward: 1.0
  max_reward_times: 1
