custom_init_commands:
- /give @s minecraft:diamond_pickaxe
- /setblock ~2 ~ ~ minecraft:chest
- /give @s minecraft:torch 20
defaults:
- base
- _self_
text: Explore and open a chest to discover its contents.
reward_cfg:
- event: use_item
  identity: open_chest
  objects:
  - chest
  reward: 10
  max_reward_times: 1
