custom_init_commands:
- /give @s minecraft:map 1
- /give @s minecraft:wooden_pickaxe 1
- /give @s minecraft:oak_boat 1
- /setblock ~2 ~ ~ minecraft:chest{LootTable:"minecraft:chests/buried_treasure"}
defaults:
- base
- _self_
text: Locate and explore a buried treasure using a treasure map.
reward_cfg:
- event: use_item
  identity: use_map
  objects:
  - map
  reward: 5
  max_reward_times: 1
- event: open_chest
  identity: open_buried_treasure_chest
  objects:
  - chest
  reward: 5.0
  max_reward_times: 1