custom_init_commands:
- /give @s minecraft:bread 32
- /give @s minecraft:iron_pickaxe
defaults:
- base
- _self_
text: Explore and climb a mountain.
reward_cfg:
- event: craft_item
  identity: craft_ladder
  objects:
  - ladder
  reward: 1.0
  max_reward_times: 5
- event: use_item
  identity: climb_ladder
  objects:
  - ladder
  reward: 1.0
  max_reward_times: 5
