custom_init_commands:
- /give @s minecraft:oak_planks 10
- /setblock ~3 ~ ~ minecraft:water
- /summon boat
defaults:
- base
- _self_
text: Build and use a boat to explore water bodies in Minecraft.
reward_cfg:
- event: craft_item
  identity: craft_boat
  objects:
  - boat
  reward: 1.0
  max_reward_times: 1
- event: use_item
  identity: use_boat
  objects:
  - boat
  reward: 1.0
  max_reward_times: 1
