custom_init_commands:
- /give @s minecraft:stone 15
- /give @s minecraft:iron_ingot 5
- /give @s minecraft:crafting_table 1
defaults:
- base
- _self_
text: Open your inventory and craft a stonecutter.
reward_cfg:
- event: craft_item
  identity: craft_stonecutter
  objects:
  - stonecutter
  reward: 10.0
  max_reward_times: 1
