custom_init_commands:
- /give @s minecraft:oak_log 10
- /give @s minecraft:crafting_table
- /give @s minecraft:apple 5
text: craft oak planks from oak logs
thinking: '- In order to craft oak planks, you need at least one oak log.'
reward_cfg:
- event: craft_item
  identity: craft_oak_planks
  objects:
  - oak_planks
  reward: 10.0
  max_reward_times: 1
