custom_init_commands:
- /give @s minecraft:shears 1
- /summon minecraft:sheep ~2 ~ ~
- /summon minecraft:sheep ~3 ~ ~
- /summon minecraft:sheep ~4 ~ ~
defaults:
- base
- _self_
text: Shear sheep to collect wool.
reward_cfg:
- event: pickup_item
  identity: collect_wool
  objects:
  - wool
  reward: 0.5
  max_reward_times: 20
