custom_init_commands:
- /give @s minecraft:shears 1
- /execute as @p at @s run fill ~3 ~1 ~3 ~-3 ~1 ~-3 minecraft:tall_grass replace
defaults:
- base
- _self_
text: Collect grass using the appropriate tool.
reward_cfg:
- event: pickup
  identity: collect_grass
  objects:
  - grass
  reward: 0.5
  max_reward_times: 20
