custom_init_commands:
- /replaceitem entity @s weapon.mainhand minecraft:diamond_pickaxe
- /execute as @p at @s run fill ~2 ~-1 ~3 ~1 ~-1 ~4 obsidian
defaults:
- base
- _self_
text: Mine obsidian blocks for various crafting or building purposes.
reward_cfg:
- event: mine_block
  identity: mine_obsidian
  objects:
  - obsidian
  reward: 10.0
  max_reward_times: 1
