custom_init_commands:
- /replaceitem entity @s weapon.mainhand minecraft:stone_pickaxe
- /execute as @p at @s run fill ~2 ~ ~2 ~3 ~1 ~3 minecraft:iron_ore
defaults:
- base
- _self_
text: Mine iron ore from the environment.
reward_cfg:
- event: mine_block
  identity: mine_iron_ore
  objects:
  - iron_ore
  reward: 1.0
  max_reward_times: 1
