custom_init_commands:
- /give @s minecraft:shears
- /execute as @p at @s run fill ~3 ~1 ~3 ~-3 ~1 ~-3 minecraft:tall_grass replace minecraft:air
text: clean the weeds
thinking: '- In order to clean the weeds, we need shears and a grassy area with tall
  grass or flowers.'
reward_cfg:
- event: mine_block
  identity: clean_grass
  objects:
  - tall_grass
  reward: 0.5
  max_reward_times: 20
