custom_init_commands:
- /time set night
- /give @s minecraft:torch 64
- /give @s minecraft:glowstone 10
text: light up the surroundings using torches at night
thinking: '- In order to light up the surroundings at night, we need torches and set
  the time to night.'
reward_cfg:
- event: use_item
  identity: use_lighting_items
  objects:
  - torch
  - glowstone
  reward: 0.5
  max_reward_times: 20
