custom_init_commands:
- /give @s minecraft:pumpkin 5
- /give @s minecraft:shears
- /setblock ~2 ~ ~ minecraft:crafting_table
defaults:
- base
- _self_
text: Carve pumpkins to create jack-o'-lanterns.
reward_cfg:
- event: craft_item
  identity: craft_jack_o_lantern
  objects:
  - lit_pumpkin
  reward: 10.0
  max_reward_times: 1
