custom_init_commands:
- /give @s minecraft:diamond_sword
- /give @s minecraft:enchanting_table
- /give @s minecraft:lapis_lazuli 15
- /give @s minecraft:book 30
- /setblock ~2 ~ ~ minecraft:enchanting_table
defaults:
- base
- _self_
text: Enchant a diamond sword using an enchanting table.
reward_cfg:
- event: use_item
  identity: enchant_item
  objects:
  - enchanting_table
  reward: 5.0
  max_reward_times: 1
