custom_init_commands:
- /give @s minecraft:flint 5
- /give @s minecraft:iron_ingot 5
- /give @s minecraft:oak_log 10
- /give @s minecraft:oak_leaves 10
- /replaceitem entity @s weapon.mainhand minecraft:flint_and_steel
defaults:
- base
- _self_
text: Use flint and steel to ignite a fire.
reward_cfg:
- event: craft_item
  identity: craft_flint_and_steel
  objects:
  - flint_and_steel
  reward: 1.0
  max_reward_times: 1
- event: use_item
  identity: ignite_fire
  objects:
  - flint_and_steel
  reward: 1.0
  max_reward_times: 1