custom_init_commands:
- /time set night
- /give @s minecraft:white_bed 1
- /setblock ~2 ~ ~ minecraft:white_bed
defaults:
- base
- _self_
text: Sleep in a bed to skip the night.
reward_cfg:
- event: use_item
  identity: sleep_in_bed
  objects:
  - white_bed
  reward: 1.0
  max_reward_times: 1