custom_init_commands:
- /give @s minecraft:shield
- /give @s minecraft:stone_sword
- /give @s minecraft:planks 20
- /give @s minecraft:stick 10
- /summon minecraft:zombie ~2 ~ ~
defaults:
- base
- _self_
text: Equip and use a shield to block incoming attacks.
reward_cfg:
- event: use_item
  identity: use_shield
  objects:
  - shield
  reward: 1.0
  max_reward_times: 1