custom_init_commands:
- /replaceitem entity @s armor.head minecraft:diamond_helmet
- /replaceitem entity @s armor.chest minecraft:diamond_chestplate
- /replaceitem entity @s armor.legs minecraft:diamond_leggings
- /replaceitem entity @s armor.feet minecraft:diamond_boots
- /replaceitem entity @s weapon.mainhand minecraft:diamond_sword
- /summon minecraft:spider ~3 ~ ~
defaults:
- base
- _self_
text: Engage in combat with spiders using appropriate weapons and armor.
reward_cfg:
- event: kill_entity
  identity: kill_spider
  objects:
  - spider
  reward: 10.0
  max_reward_times: 1
