custom_init_commands:
- /summon minecraft:horse ~3 ~ ~
- /summon minecraft:horse ~1 ~ ~
- /give @s minecraft:bow
- /give @s minecraft:arrow 64
- /give @s minecraft:iron_sword
- /give @s minecraft:golden_carrot 10
text: hunt a horse using a sword or bow
thinking: '- In order to hunt a horse, we need a weapon, such as a sword or bow, and
  have a horse nearby.'
reward_cfg:
- event: kill_entity
  identity: kill_horse
  objects:
  - horse
  reward: 5.0
  max_reward_times: 2
