custom_init_commands:
- /give @s minecraft:stick 32
- /give @s minecraft:crafting_table 1
- /give @s minecraft:oak_planks 16
- /give @s minecraft:torch 10
text: build a ladder using sticks
thinking: '- In order to build a ladder, we need at least 7 sticks to craft a ladder
  using a crafting table.'
reward_cfg:
- event: craft_item
  identity: craft_ladder
  objects:
  - ladder
  reward: 1
  max_reward_times: 1
- event: use_item
  identity: place_ladder
  objects:
  - ladder
  reward: 1
  max_reward_times: 1
