custom_init_commands:
- /replaceitem entity @s weapon.mainhand minecraft:fishing_rod
- /give @s minecraft:fishing_rod 2
- /summon minecraft:chicken ~1 ~ ~-1
- /summon minecraft:chicken ~-2 ~ ~2
- /give @s minecraft:seeds 10
text: hook a chicken with a fishing rod
thinking: '- In order to hook a chicken using a fishing rod, we need a fishing rod
  and a chicken nearby.'
reward_cfg:
- event: use_item
  identity: use_fishing_rod
  objects:
  - fishing_rod
  reward: 2.0
  max_reward_times: 5
