custom_init_commands:
- /give @s minecraft:carpet 32
- /give @s minecraft:flower_pot 10
- /give @s minecraft:red_tulip 10
- /give @s minecraft:blue_orchid 10
- /give @s minecraft:torch 10
- /give @s minecraft:glowstone 10
text: decorate the ground with colorful items
thinking: '- In order to decorate the ground, you may need various decorative blocks
  such as carpet, flower pots, and flowers.'
reward_cfg:
- event: use_item
  identity: decorate_ground
  objects:
  - carpet
  - flower_pot
  - red_tulip
  - blue_orchid
  - torch
  - glowstone
  reward: 0.25
  max_reward_times: 40
