custom_init_commands:
- /execute as @p at @s run fill ~2 ~ ~2 ~4 ~ ~4 minecraft:melon
- /give @p minecraft:shears
text: find a melon
thinking: '- In order to find a melon, we need to make sure there are melon blocks
  nearby. Melons can be found naturally in jungles or savanna villages.'
reward_cfg:
- event: mine_block
  identity: mine_melon_block
  objects:
  - melon_block
  reward: 10.0
  max_reward_times: 1
